### ISSUE TITLE
Apr 13 milestone

### ISSUE THREAD

**Issue by nadeemabdulhamid** [HunBurry/hon450-451#1]
Apr 13 - using TextBlob to do a basic classification task on data collected (tweet noun phrases --> state predictor/probability reporter)

**Comment by HunBurry** [comment]
Files should be in the latest Git Commit, as well as some addition files as well. I've added comments where necessary. Also, as an addition note, some of the files may have 'memory errors' based on the amount of RAM available at the time the file is running and the size of the batch. If it errors out, just lower the batch size and it _should_ work.
